image: "python:3.8"

before_script:
  - python --version
  - pip3 install flake8 pytest-asyncio async_property

stages:
  - test

test:
  stage: test
  script:
  - flake8 --max-line-length=120 neohubapi/*.py
  - flake8 --max-line-length=120 tests/*.py
  - flake8 --max-line-length=120 scripts/*.py
  - python -m pytest
